CREATE TABLE worker (
    ID BIGINT UNIQUE,
	NAME VARCHAR(1000) CHECK (LENGTH(NAME) BETWEEN 2 AND 1000),
    BIRTHDAY DATE CHECK (BIRTHDAY >= '1900-01-01'),
	LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK (SALARY>=100 AND SALARY<=100000)
);
CREATE TABLE client(
	ID BIGINT UNIQUE,
	NAME VARCHAR(1000) CHECK (LENGTH(NAME) BETWEEN 2 AND 1000)	
);
CREATE TABLE project(
	ID BIGINT UNIQUE,
	CLIENT_ID INT REFERENCES client(ID),
	START_DATE DATE DEFAULT CURRENT_DATE,
	FINISH_DATE DATE
);
CREATE TABLE project_worker (
    PROJECT_ID BIGINT REFERENCES project(ID),
    WORKER_ID BIGINT REFERENCES worker(ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
)	